name: Increment Semantic Version
uses: christian-draeger/increment-semantic-version@1.1.0

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  - name: Bump release version
    id: bump_version
    uses: christian-draeger/increment-semantic-version@1.1.0
    with:
      current-version: '2.11.7-alpha.3' # also accepted: 'v2.11.7-alpha.3' | '2.11.7-alpha3'
      version-fragment: 'feature'
  - name: Do something with your bumped release version
    run: echo ${{ steps.bump_version.outputs.next-version }}
    # will print 2.12.0
